### ISSUE TITLE
Add the ability to include ilvl 75+ to chaos recipe

### ISSUE THREAD

**Issue by thebeast792** [darvid/stashvision#4]
It seems like stashvision only limits looking at ilvl 60-74 gear for all pieces for a chaos recipe. However, if you have all the rares at ilvl75+ but one rare at ilvl 60-74, the chaos recipe still works. Can you please add this feature that makes the ilvl75+ portion work?

**Comment by darvid** [comment]
should be fixed in v0.1.2

**Comment by thebeast792** [comment]
It seems like the chaos recipe worked sometimes but now it's highlighting these two weapons for some reason even though a chaos set exists in this stash tab:

https://i.imgur.com/dPS9UDc.png

(Note that I changed the league to Standard in the script to test this before Harvest. I can see it pulling data from standard in the log file)


Also, I noticed in the log file that some of the new line characters "\n" seem to be printed out instead of actually creating a new line. This is for the "matches" debug printout line.

**Comment by darvid** [comment]
Hmm...I'll have to try and reproduce - did you get this behavior by using the hotkey in succession to walk through multiple item sets? 

Also what item levels are the two weapons being highlighted in your stash?

**Comment by thebeast792** [comment]
Yes, I tried pressing shift+alt+c multiple times but it does not change the highlights.

The two weapons are wand ilvl 75 and vaal axe ilvl 86.

**Comment by thebeast792** [comment]
I took out the axe and rearranged the items a bit. The set on the right is all ilvl62+ (at least one is in the ilvl 60-74 and at least one is in ilvl 75+). It's not highlighting any items at all.

https://i.imgur.com/8zBZqoo.png

**Comment by darvid** [comment]
Okay I can't seem to reproduce. My dump tab has the following:

* At least one full chaos recipe set
* Multiple ilvl 84+ items, including weapons (1h and 2h)

Could you try the following:

* Stop the script and delete the ``stash_tabs.bleve`` directory (this should be in the **stashvision-go** directory, but delete it in the root directory as well if it exists)
* Delete ``server.log``
* Download stashvision.exe from here: https://github.com/darvid/stashvision/suites/814999508/artifacts/8926543 -- this is functionally the same as v0.1.2 but has some better item logging which might help troubleshoot
* Drop the new stashvision.exe in the **stashvision-go** directory and rerun the AHK

It should take a few seconds to re-index and then you can try to reproduce. If you can still reproduce, could you please attach the ``server.log``? 

Also, if you can reproduce it again, and you're comfortable with the command line, please try the following:

* Open a cmd and navigate to the directory with stashvision.exe (**stashvision-go**)
* Run ``stashvision.exe r -n=unid_chaos -p -t=0 -v`` and paste the output here (change ``-t=0`` to whatever the value of your tab index is, it might not be 0)

**Comment by thebeast792** [comment]
Seems like it isn't picking up on all the weapons.

[server.log](https://github.com/darvid/stashvision/files/4801361/server.log)
[output.txt](https://github.com/darvid/stashvision/files/4801362/output.txt)

**Comment by darvid** [comment]
hm. Rune Dagger is missing as a base class, but that alone wouldn't explain why it's trying to make a set with two weapons...at least I don't think. 

What happens when you remove the rune dagger from the tab and re-index (either wait 10s with stashvision running before using the hotkey again, or exit and rerun completely)?

**Comment by thebeast792** [comment]
> What happens when you remove the rune dagger from the tab and re-index (either wait 10s with stashvision running before using the hotkey again, or exit and rerun completely)?

It's finding a recipe with the Vaal Axe. I've been changing things around in the stash. The recipe works again with more weapons but ya it's not recognizing rune daggers. That should be an easy fix?

**Comment by darvid** [comment]
yep easy fix - I'm trying to fix #5 as well if possible, but should get a new release out with the fix either way soon

**Comment by darvid** [comment]
should be fixed in this build:

https://github.com/darvid/stashvision/suites/815771597/artifacts/8944296

**Comment by thebeast792** [comment]
I followed the instructions from before and still get the same issues.
-It's not using Rune Daggers
-It highlighted a dagger and Vaal axe as a chaos recipe set
-(new?) It reused the same wand for 2 of the 4 sets.
[server.log](https://github.com/darvid/stashvision/files/4802135/server.log)
[output.txt](https://github.com/darvid/stashvision/files/4802136/output.txt)

**Comment by darvid** [comment]
oh man, one step forward two steps back lol. thanks for your patience and for helping test!

this build should finally fix the rune daggers issue:

https://github.com/darvid/stashvision/suites/815855923/artifacts/8946084

as for using the same wand, that's probably due to me trying to fix #5 (which was caused by the fix for this, ilvl 74+ support, whee), but might be harder to pin down...

**Comment by thebeast792** [comment]
I'm happy to help! 

That last build seems to have fixed issues 1 & 2, which is great! The only issue remaining is the re-use of the wand (and some other stuff get re-used in some of the sets, too).

[server.log](https://github.com/darvid/stashvision/files/4802261/server.log)
[output.txt](https://github.com/darvid/stashvision/files/4802262/output.txt)

**Comment by darvid** [comment]
alright, I'm flying blind here because I don't have a lot of chaos recipe rares on standard, but this build should theoretically fix the re-use of items issue.

https://github.com/darvid/stashvision/suites/815959119/artifacts/8948532

**Comment by thebeast792** [comment]
Same issue. I think the sets are the same, too.

**Comment by darvid** [comment]
ok, finally farmed some rares in standard so I could debug... this build should finally fix the duplicate items across sets, fingers crossed it works for you as well:

https://github.com/darvid/stashvision/suites/816135764/artifacts/8952052

once you test, I'll cut a new release

**Comment by thebeast792** [comment]
I think it's working! Nice!

**Comment by thebeast792** [comment]
Can you please release this before the league start?

**Comment by darvid** [comment]
yep - https://github.com/darvid/stashvision/releases/tag/v0.1.3
